import random
import pandas as pd

hotels = [
    {"hotel_name": "Hotel Himalaya", "address": "123 Main Street, Srinagar, Jammu and Kashmir"},
    {"hotel_name": "Royal Palace Hotel", "address": "456 Lakeview Road, Gulmarg, Jammu and Kashmir"},
    {"hotel_name": "Mountain View Inn", "address": "789 Hillside Avenue, Pahalgam, Jammu and Kashmir"},
    {"hotel_name": "Snowy Peaks Resort", "address": "101 Pinecrest Drive, Sonamarg, Jammu and Kashmir"},
    {"hotel_name": "Kashmir Paradise Lodge", "address": "234 Lakeside Road, Dal Lake, Srinagar, Jammu and Kashmir"},
    {"hotel_name": "Meadow Retreat Hotel", "address": "567 Riverbank Road, Baramulla, Jammu and Kashmir"},
    {"hotel_name": "Golden Tulip Resort", "address": "890 Mountainview Lane, Gulmarg, Jammu and Kashmir"},
    {"hotel_name": "Lakeside Inn", "address": "321 Dal Lake Boulevard, Srinagar, Jammu and Kashmir"},
    {"hotel_name": "Pine Valley Resort", "address": "432 Hilltop Road, Pahalgam, Jammu and Kashmir"},
    {"hotel_name": "Majestic View Hotel", "address": "765 Glacier Avenue, Sonamarg, Jammu and Kashmir"},
    {"hotel_name": "Green Meadows Retreat", "address": "543 Forestview Lane, Baramulla, Jammu and Kashmir"},
    {"hotel_name": "Alpine Heights Lodge", "address": "678 Mountain Ridge Road, Gulmarg, Jammu and Kashmir"},
    {"hotel_name": "Riverfront Retreat", "address": "987 Riverside Drive, Pahalgam, Jammu and Kashmir"},
    {"hotel_name": "Sapphire Hotel", "address": "876 Sapphire Street, Srinagar, Jammu and Kashmir"},
    {"hotel_name": "Himalayan Peaks Resort", "address": "210 Mountainview Road, Sonamarg, Jammu and Kashmir"},
    {"hotel_name": "Paradise Valley Lodge", "address": "345 Paradise Lane, Gulmarg, Jammu and Kashmir"},
    {"hotel_name": "Dal Lakeview Hotel", "address": "654 Lakeside Drive, Srinagar, Jammu and Kashmir"},
    {"hotel_name": "Riverbank Retreat", "address": "789 Riverside Avenue, Pahalgam, Jammu and Kashmir"},
    {"hotel_name": "Misty Mountains Inn", "address": "543 Hillcrest Lane, Sonamarg, Jammu and Kashmir"},
    {"hotel_name": "Kashmiri Haven Resort", "address": "321 Riverside Road, Gulmarg, Jammu and Kashmir"},
    {"hotel_name": "Himalayan View Shimla", "address": "123 Ridge Road, Shimla, Himachal Pradesh"},
    {"hotel_name": "Royal Retreat Manali", "address": "456 Mall Road, Manali, Himachal Pradesh"},
    {"hotel_name": "Mountain Bliss Dharamshala", "address": "789 Pinecrest Avenue, Dharamshala, Himachal Pradesh"},
    {"hotel_name": "Snowy Peaks Kullu", "address": "101 Valley Road, Kullu, Himachal Pradesh"},
    {"hotel_name": "Himalayan Paradise Kasauli", "address": "234 Hillside Road, Kasauli, Himachal Pradesh"},
    {"hotel_name": "Misty Meadows Chamba", "address": "567 Riverfront Lane, Chamba, Himachal Pradesh"},
    {"hotel_name": "Golden Hills Palampur", "address": "890 Mountainview Road, Palampur, Himachal Pradesh"},
    {"hotel_name": "Lakeside Mandi", "address": "321 Lakeview Boulevard, Mandi, Himachal Pradesh"},
    {"hotel_name": "Pine Valley Dalhousie", "address": "432 Hilltop Drive, Dalhousie, Himachal Pradesh"},
    {"hotel_name": "Himalayan View Dharamshala", "address": "654 Ridge Lane, Dharamshala, Himachal Pradesh"},
    {"hotel_name": "Green Haven Inn Manali", "address": "543 Forestview Road, Manali, Himachal Pradesh"},
    {"hotel_name": "Alpine Heights Dharamshala", "address": "678 Mountain Ridge Avenue, Dharamshala, Himachal Pradesh"},
    {"hotel_name": "Riverfront Oasis Kullu", "address": "987 Riverside Road, Kullu, Himachal Pradesh"},
    {"hotel_name": "Sapphire Hills Kasauli", "address": "876 Sapphire Lane, Kasauli, Himachal Pradesh"},
    {"hotel_name": "Himalayan Peaks Palampur", "address": "210 Valley Drive, Palampur, Himachal Pradesh"},
    {"hotel_name": "Paradise Valley Mandi", "address": "345 Paradise Road, Mandi, Himachal Pradesh"},
    {"hotel_name": "Dalhousie Lakeview Dalhousie", "address": "654 Lakefront Avenue, Dalhousie, Himachal Pradesh"},
    {"hotel_name": "Riverbank Haven Chamba", "address": "789 Riverside Lane, Chamba, Himachal Pradesh"},
    {"hotel_name": "Misty Hills Shimla", "address": "543 Hillcrest Road, Shimla, Himachal Pradesh"},
    {"hotel_name": "Kullu Haven Resort", "address": "321 Valleyview Lane, Kullu, Himachal Pradesh"},
    {"hotel_name": "Punjab Palace Amritsar", "address": "123 Golden Temple Road, Amritsar, Punjab"},
    {"hotel_name": "Royal Retreat Ludhiana", "address": "456 Mall Road, Ludhiana, Punjab"},
    {"hotel_name": "Golden Gardens Jalandhar", "address": "789 Model Town, Jalandhar, Punjab"},
    {"hotel_name": "Green Valley Chandigarh", "address": "101 Sector 22, Chandigarh, Punjab"},
    {"hotel_name": "Saffron Suites Patiala", "address": "234 Civil Lines, Patiala, Punjab"},
    {"hotel_name": "Majestic View Resort", "address": "567 Grand Trunk Road, Amritsar, Punjab"},
    {"hotel_name": "Riverfront Retreat Bathinda", "address": "890 Mall Road, Bathinda, Punjab"},
    {"hotel_name": "City Lights Mohali", "address": "321 Sector 70, Mohali, Punjab"},
    {"hotel_name": "Grand Plaza Moga", "address": "432 Ferozepur Road, Moga, Punjab"},
    {"hotel_name": "Punjab Heights Ludhiana", "address": "654 Dugri Road, Ludhiana, Punjab"},
    {"hotel_name": "Heritage Inn Chandigarh", "address": "543 Sector 35, Chandigarh, Punjab"},
    {"hotel_name": "Golden Tulip Amritsar", "address": "678 Queens Road, Amritsar, Punjab"},
    {"hotel_name": "City Lights Jalandhar", "address": "987 GT Road, Jalandhar, Punjab"},
    {"hotel_name": "Sapphire Hotel Patiala", "address": "876 Mall Road, Patiala, Punjab"},
    {"hotel_name": "Misty Meadows Resort", "address": "210 Green Avenue, Ludhiana, Punjab"},
    {"hotel_name": "Riverbank Oasis Mohali", "address": "345 Phase 3B2, Mohali, Punjab"},
    {"hotel_name": "Punjab Paradise Pathankot", "address": "654 Patel Chowk, Pathankot, Punjab"},
    {"hotel_name": "Sunset View Hoshiarpur", "address": "789 Civil Lines, Hoshiarpur, Punjab"},
    {"hotel_name": "Hilltop Lodge Faridkot", "address": "543 Kotkapura Road, Faridkot, Punjab"},
    {"hotel_name": "Garden Retreat Barnala", "address": "321 Circular Road, Barnala, Punjab"},
    {"hotel_name": "Uttarakhand Heights Dehradun", "address": "123 Rajpur Road, Dehradun, Uttarakhand"},
    {"hotel_name": "Royal Retreat Nainital", "address": "456 Mallital, Nainital, Uttarakhand"},
    {"hotel_name": "Mountain View Resort Mussoorie", "address": "789 Camel's Back Road, Mussoorie, Uttarakhand"},
    {"hotel_name": "Snowy Peaks Hotel Auli", "address": "101 Auli Road, Auli, Uttarakhand"},
    {"hotel_name": "Himalayan Paradise Ranikhet", "address": "234 Majhkhali, Ranikhet, Uttarakhand"},
    {"hotel_name": "Misty Meadows Almora", "address": "567 Mall Road, Almora, Uttarakhand"},
    {"hotel_name": "Golden Hills Kausani", "address": "890 View Point, Kausani, Uttarakhand"},
    {"hotel_name": "Lakeside Retreat Bhimtal", "address": "321 Sattal Road, Bhimtal, Uttarakhand"},
    {"hotel_name": "Pine Valley Lodge Pithoragarh", "address": "432 Bageshwar Road, Pithoragarh, Uttarakhand"},
    {"hotel_name": "Uttarakhand View Rishikesh", "address": "654 Haridwar Road, Rishikesh, Uttarakhand"},
    {"hotel_name": "Green Haven Resort Haridwar", "address": "543 Raiwala, Haridwar, Uttarakhand"},
    {"hotel_name": "Alpine Heights Corbett", "address": "678 Jim Corbett Park Road, Corbett, Uttarakhand"},
    {"hotel_name": "Riverfront Oasis Pauri", "address": "987 Kandoliya, Pauri, Uttarakhand"},
    {"hotel_name": "Sapphire Hills Tehri", "address": "876 New Tehri, Tehri, Uttarakhand"},
    {"hotel_name": "Himalayan Peaks Chamoli", "address": "210 Joshimath, Chamoli, Uttarakhand"},
    {"hotel_name": "Paradise Valley Rudraprayag", "address": "345 Agastyamuni, Rudraprayag, Uttarakhand"},
    {"hotel_name": "Dalhousie Lakeview Uttarkashi", "address": "654 Gangotri Road, Uttarkashi, Uttarakhand"},
    {"hotel_name": "Riverbank Haven Bageshwar", "address": "789 Baijnath, Bageshwar, Uttarakhand"},
    {"hotel_name": "Misty Hills Mukteshwar", "address": "543 Sitla, Mukteshwar, Uttarakhand"},
    {"hotel_name": "Uttarakhand Haven Haldwani", "address": "321 Kaladhungi Road, Haldwani, Uttarakhand"},
    {"hotel_name": "Sunrise Inn", "address": "123 MG Road, Gurgaon, Haryana"},
    {"hotel_name": "Palm Breeze Hotel", "address": "456 Mathura Road, Faridabad, Haryana"},
    {"hotel_name": "Hillside Retreat", "address": "789 Jhajjar Road, Rohtak, Haryana"},
    {"hotel_name": "Tranquil Valley Resort", "address": "101 Model Town, Ambala, Haryana"},
    {"hotel_name": "Golden Meadows Lodge", "address": "234 GT Road, Panipat, Haryana"},
    {"hotel_name": "Mystic Haven", "address": "567 Railway Road, Karnal, Haryana"},
    {"hotel_name": "Emerald Oasis", "address": "890 Sirsa Road, Hisar, Haryana"},
    {"hotel_name": "Lakeside Serenity", "address": "321 Jagadhri Road, Yamunanagar, Haryana"},
    {"hotel_name": "Pine Ridge Lodge", "address": "432 Sector 5, Panchkula, Haryana"},
    {"hotel_name": "Tranquility Inn", "address": "654 Civil Lines, Ambala, Haryana"},
    {"hotel_name": "Sapphire Hotel", "address": "543 Hansi Road, Bhiwani, Haryana"},
    {"hotel_name": "Harmony Haven", "address": "678 Rohtak Road, Jind, Haryana"},
    {"hotel_name": "Alpine Heights", "address": "987 Patiala Road, Kaithal, Haryana"},
    {"hotel_name": "Riverfront Residency", "address": "876 Sirsa Road, Fatehabad, Haryana"},
    {"hotel_name": "Valley Vista Hotel", "address": "210 University Road, Kurukshetra, Haryana"},
    {"hotel_name": "Serenade Lodge", "address": "345 NH-2, Palwal, Haryana"},
    {"hotel_name": "Hilltop Oasis", "address": "654 Bahadurgarh Road, Jhajjar, Haryana"},
    {"hotel_name": "Riverbank Retreat", "address": "789 NH-8, Rewari, Haryana"},
    {"hotel_name": "Misty Pines Resort", "address": "543 Murthal Road, Sonipat, Haryana"},
    {"hotel_name": "Green Valley Inn", "address": "321 Delhi Road, Rohtak, Haryana"},
    {"hotel_name": "Royal Palace Hotel", "address": "123 Palace Road, Jaipur, Rajasthan"},
    {"hotel_name": "Desert Oasis Resort", "address": "456 Sand Dune Lane, Jaisalmer, Rajasthan"},
    {"hotel_name": "Udaipur Retreat", "address": "789 Lakeview Road, Udaipur, Rajasthan"},
    {"hotel_name": "Mount Abu Inn", "address": "101 Hill Station Road, Mount Abu, Rajasthan"},
    {"hotel_name": "Ajmer Paradise Lodge", "address": "234 Pushkar Road, Ajmer, Rajasthan"},
    {"hotel_name": "Jodhpur Hills Hotel", "address": "567 Mehrangarh Fort Road, Jodhpur, Rajasthan"},
    {"hotel_name": "Bikaner Heritage Resort", "address": "890 Camel Festival Lane, Bikaner, Rajasthan"},
    {"hotel_name": "Ranthambore Retreat", "address": "321 Tiger Reserve Road, Ranthambore, Rajasthan"},
    {"hotel_name": "Kota Valley Lodge", "address": "432 Chambal River Road, Kota, Rajasthan"},
    {"hotel_name": "Haweli Inn Jaipur", "address": "654 Pink City Road, Jaipur, Rajasthan"},
    {"hotel_name": "Green Haven Pushkar", "address": "543 Ghati Road, Pushkar, Rajasthan"},
    {"hotel_name": "Alwar Heights Resort", "address": "678 Sariska Tiger Reserve Road, Alwar, Rajasthan"},
    {"hotel_name": "Riverfront Oasis Jaisalmer", "address": "987 Gadisar Lake Road, Jaisalmer, Rajasthan"},
    {"hotel_name": "Sapphire Hotel Udaipur", "address": "876 Fateh Sagar Lake Road, Udaipur, Rajasthan"},
    {"hotel_name": "Chittorgarh Peaks Hotel", "address": "210 Chittorgarh Fort Road, Chittorgarh, Rajasthan"},
    {"hotel_name": "Paradise Valley Kota", "address": "345 Seven Wonders Road, Kota, Rajasthan"},
    {"hotel_name": "Mount Abu Lakeview Inn", "address": "654 Nakki Lake Road, Mount Abu, Rajasthan"},
    {"hotel_name": "Bharatpur Haven Lodge", "address": "789 Keoladeo National Park Road, Bharatpur, Rajasthan"},
    {"hotel_name": "Hilltop Retreat Sikar", "address": "543 Fatehpur Road, Sikar, Rajasthan"},
    {"hotel_name": "Jaisalmer Sands Resort", "address": "321 Sam Sand Dunes Road, Jaisalmer, Rajasthan"},
    {"hotel_name": "New Delhi Grand Hotel", "address": "123 Connaught Place, New Delhi, Delhi"},
    {"hotel_name": "Deluxe Inn", "address": "456 Karol Bagh, New Delhi, Delhi"},
    {"hotel_name": "Elegance Suites", "address": "789 Paharganj, New Delhi, Delhi"},
    {"hotel_name": "Metro View Hotel", "address": "101 Rajendra Place, New Delhi, Delhi"},
    {"hotel_name": "Green Park Residency", "address": "234 Green Park, New Delhi, Delhi"},
    {"hotel_name": "Urban Oasis Inn", "address": "567 South Extension, New Delhi, Delhi"},
    {"hotel_name": "Sunrise Hotel", "address": "890 Chandni Chowk, New Delhi, Delhi"},
    {"hotel_name": "Cityscape Lodge", "address": "321 Lajpat Nagar, New Delhi, Delhi"},
    {"hotel_name": "Golden Triangle Resort", "address": "432 Saket, New Delhi, Delhi"},
    {"hotel_name": "Capital City Inn", "address": "654 Dwarka, New Delhi, Delhi"},
    {"hotel_name": "Paharganj Paradise", "address": "543 Paharganj, New Delhi, Delhi"},
    {"hotel_name": "Delhi Heights Hotel", "address": "678 Karol Bagh, New Delhi, Delhi"},
    {"hotel_name": "Central Plaza", "address": "987 Connaught Place, New Delhi, Delhi"},
    {"hotel_name": "Sapphire Suites", "address": "876 South Delhi, New Delhi, Delhi"},
    {"hotel_name": "Majestic View Hotel", "address": "210 Rajouri Garden, New Delhi, Delhi"},
    {"hotel_name": "Palm Breeze Inn", "address": "345 Greater Kailash, New Delhi, Delhi"},
    {"hotel_name": "South Extension Lodge", "address": "654 South Extension, New Delhi, Delhi"},
    {"hotel_name": "Delhi Gate Hotel", "address": "789 Chandni Chowk, New Delhi, Delhi"},
    {"hotel_name": "Lajpat Nagar Retreat", "address": "543 Lajpat Nagar, New Delhi, Delhi"},
    {"hotel_name": "Chandni Chowk Palace", "address": "321 Chandni Chowk, New Delhi, Delhi"},
    {"hotel_name": "Taj Mahal View Hotel", "address": "123 Agra Cantt, Uttar Pradesh"},
    {"hotel_name": "Ganges Riverside Resort", "address": "456 Varanasi Ghat, Uttar Pradesh"},
    {"hotel_name": "Lucknow Heights", "address": "789 Hazratganj, Uttar Pradesh"},
    {"hotel_name": "Grand Inn Kanpur", "address": "101 Civil Lines, Uttar Pradesh"},
    {"hotel_name": "Prayagraj Palace", "address": "234 Sangam Marg, Uttar Pradesh"},
    {"hotel_name": "Mathura Retreat", "address": "567 Vrindavan Road, Uttar Pradesh"},
    {"hotel_name": "Noida Grand Hotel", "address": "890 Sector 18, Uttar Pradesh"},
    {"hotel_name": "Gorakhpur Vista", "address": "321 Golghar, Uttar Pradesh"},
    {"hotel_name": "Taj Residency Agra", "address": "432 Fatehabad Road, Uttar Pradesh"},
    {"hotel_name": "Allahabad Inn", "address": "654 Civil Lines, Uttar Pradesh"},
    {"hotel_name": "Faizabad Heights", "address": "543 Ayodhya Road, Uttar Pradesh"},
    {"hotel_name": "Ayodhya Palace", "address": "678 Ram Janmabhoomi, Uttar Pradesh"},
    {"hotel_name": "Varanasi Ghatview Lodge", "address": "987 Dashashwamedh Ghat, Uttar Pradesh"},
    {"hotel_name": "Sapphire Hotel Lucknow", "address": "876 Gomti Nagar, Uttar Pradesh"},
    {"hotel_name": "Meerut Meadows Resort", "address": "210 Mawana Road, Uttar Pradesh"},
    {"hotel_name": "Lakeview Inn Kanpur", "address": "345 Bithoor Road, Uttar Pradesh"},
    {"hotel_name": "Ghaziabad Hills Hotel", "address": "654 Indirapuram, Uttar Pradesh"},
    {"hotel_name": "Fortview Lodge Agra", "address": "789 Tajganj, Uttar Pradesh"},
    {"hotel_name": "Jhansi Heritage Inn", "address": "543 Civil Lines, Uttar Pradesh"},
    {"hotel_name": "Gomti Nagar Retreat", "address": "321 Gomti Nagar, Uttar Pradesh"},
    {"hotel_name": "Patna Grand Hotel", "address": "123 Patliputra Colony, Patna, Bihar"},
    {"hotel_name": "Bodh Gaya Retreat", "address": "456 Bodh Gaya Road, Bodh Gaya, Bihar"},
    {"hotel_name": "Muzaffarpur Heights", "address": "789 Civil Lines, Muzaffarpur, Bihar"},
    {"hotel_name": "Gaya Grand Inn", "address": "101 Gaya Road, Gaya, Bihar"},
    {"hotel_name": "Nalanda Palace", "address": "234 Nalanda University Road, Nalanda, Bihar"},
    {"hotel_name": "Darbhanga Meadows", "address": "567 Laheriasarai, Darbhanga, Bihar"},
    {"hotel_name": "Golden Triangle Resort", "address": "890 Sitamarhi, Bihar"},
    {"hotel_name": "Purnia Vista", "address": "321 Purnia Road, Purnia, Bihar"},
    {"hotel_name": "Bhagalpur Valley Lodge", "address": "432 Bhagalpur City, Bhagalpur, Bihar"},
    {"hotel_name": "Bihar Sharif Retreat", "address": "654 Bari Road, Bihar Sharif, Bihar"},
    {"hotel_name": "Chapra Paradise", "address": "543 Saran District, Chapra, Bihar"},
    {"hotel_name": "Arrah Heights", "address": "678 Arrah City, Arrah, Bihar"},
    {"hotel_name": "Sasaram Oasis Lodge", "address": "987 Rohtas District, Sasaram, Bihar"},
    {"hotel_name": "Motihari Sapphire Hotel", "address": "876 Motihari Town, Motihari, Bihar"},
    {"hotel_name": "Sitamarhi Peaks Hotel", "address": "210 Sitamarhi Town, Sitamarhi, Bihar"},
    {"hotel_name": "Buxar Valley Inn", "address": "345 Buxar District, Buxar, Bihar"},
    {"hotel_name": "Madhubani Paradise", "address": "654 Madhubani City, Madhubani, Bihar"},
    {"hotel_name": "Siwan Lakeview Inn", "address": "789 Siwan Town, Siwan, Bihar"},
    {"hotel_name": "Katihar Hills Hotel", "address": "543 Katihar District, Katihar, Bihar"},
    {"hotel_name": "Jamui Misty Meadows", "address": "321 Jamui Town, Jamui, Bihar"},
    {"hotel_name": "Gangtok Heights", "address": "123 MG Marg, Gangtok, Sikkim"},
    {"hotel_name": "Pelling Retreat", "address": "456 Pelling Road, Pelling, Sikkim"},
    {"hotel_name": "Lachung Valley Lodge", "address": "789 Lachung, Sikkim"},
    {"hotel_name": "Ravangla Grand Inn", "address": "101 Ravangla, Sikkim"},
    {"hotel_name": "Namchi Palace", "address": "234 Namchi, Sikkim"},
    {"hotel_name": "Geyzing Meadows", "address": "567 Geyzing, Sikkim"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Yuksom, Sikkim"},
    {"hotel_name": "Gyalshing Vista", "address": "321 Gyalshing, Sikkim"},
    {"hotel_name": "Rinchenpong Valley Lodge", "address": "432 Rinchenpong, Sikkim"},
    {"hotel_name": "Soreng Retreat", "address": "654 Soreng, Sikkim"},
    {"hotel_name": "Royal Retreat", "address": "123 Kolkata, West Bengal"},
    {"hotel_name": "Hillside Lodge", "address": "456 Darjeeling, West Bengal"},
    {"hotel_name": "Seaside Resort", "address": "789 Digha, West Bengal"},
    {"hotel_name": "Riverside Inn", "address": "101 Siliguri, West Bengal"},
    {"hotel_name": "Mangrove Retreat", "address": "234 Sundarbans, West Bengal"},
    {"hotel_name": "Santiniketan Oasis", "address": "567 Santiniketan, West Bengal"},
    {"hotel_name": "Golden Beach Resort", "address": "890 Shankarpur, West Bengal"},
    {"hotel_name": "Tea Garden Lodge", "address": "321 Jalpaiguri, West Bengal"},
    {"hotel_name": "Jungle Safari Lodge", "address": "432 Jaldapara, West Bengal"},
    {"hotel_name": "Beachside Haven", "address": "654 Tajpur, West Bengal"},
    {"hotel_name": "Dooars Retreat", "address": "543 Dooars, West Bengal"},
    {"hotel_name": "Bishnupur Palace", "address": "678 Bishnupur, West Bengal"},
    {"hotel_name": "Himalayan Views", "address": "987 Kalimpong, West Bengal"},
    {"hotel_name": "Forest Hills Resort", "address": "876 Cooch Behar, West Bengal"},
    {"hotel_name": "Murshidabad Palace", "address": "210 Murshidabad, West Bengal"},
    {"hotel_name": "Foothills Lodge", "address": "345 Alipurduar, West Bengal"},
    {"hotel_name": "Mayapur Paradise", "address": "654 Mayapur, West Bengal"},
    {"hotel_name": "Bakkhali Beachview Inn", "address": "789 Bakkhali, West Bengal"},
    {"hotel_name": "Sagar Island Retreat", "address": "543 Sagar Island, West Bengal"},
    {"hotel_name": "Malda Heights", "address": "321 Malda, West Bengal"},
    {"hotel_name": "Arunachal Heights", "address": "123 Itanagar, Arunachal Pradesh"},
    {"hotel_name": "Tawang Retreat", "address": "456 Tawang, Arunachal Pradesh"},
    {"hotel_name": "Bomdila View Lodge", "address": "789 Bomdila, Arunachal Pradesh"},
    {"hotel_name": "Pasighat Grand Inn", "address": "101 Pasighat, Arunachal Pradesh"},
    {"hotel_name": "Ziro Paradise", "address": "234 Ziro, Arunachal Pradesh"},
    {"hotel_name": "Dirang Meadows", "address": "567 Dirang, Arunachal Pradesh"},
    {"hotel_name": "Golden Valley Resort", "address": "890 Tezu, Arunachal Pradesh"},
    {"hotel_name": "Namsai Vista", "address": "321 Namsai, Arunachal Pradesh"},
    {"hotel_name": "Aalo Hills Hotel", "address": "432 Aalo, Arunachal Pradesh"},
    {"hotel_name": "Khonsa Valley Lodge", "address": "654 Khonsa, Arunachal Pradesh"},
    {"hotel_name": "Roing Retreat", "address": "543 Roing, Arunachal Pradesh"},
    {"hotel_name": "Daporijo Palace", "address": "678 Daporijo, Arunachal Pradesh"},
    {"hotel_name": "Naharlagun Oasis Lodge", "address": "987 Naharlagun, Arunachal Pradesh"},
    {"hotel_name": "Anini Sapphire Hotel", "address": "876 Anini, Arunachal Pradesh"},
    {"hotel_name": "Tuting Peaks Hotel", "address": "210 Tuting, Arunachal Pradesh"},
    {"hotel_name": "Assam Grand Hotel", "address": "123 Guwahati, Assam"},
    {"hotel_name": "Kaziranga Retreat", "address": "456 Kaziranga, Assam"},
    {"hotel_name": "Tezpur Heights", "address": "789 Tezpur, Assam"},
    {"hotel_name": "Jorhat Grand Inn", "address": "101 Jorhat, Assam"},
    {"hotel_name": "Dibrugarh Palace", "address": "234 Dibrugarh, Assam"},
    {"hotel_name": "Sibsagar Meadows", "address": "567 Sibsagar, Assam"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Silchar, Assam"},
    {"hotel_name": "Nagaon Vista", "address": "321 Nagaon, Assam"},
    {"hotel_name": "Bongaigaon Valley Lodge", "address": "432 Bongaigaon, Assam"},
    {"hotel_name": "Goalpara Oasis Hotel", "address": "654 Goalpara, Assam"},
    {"hotel_name": "Hailakandi Retreat", "address": "543 Hailakandi, Assam"},
    {"hotel_name": "Karimganj Palace", "address": "678 Karimganj, Assam"},
    {"hotel_name": "Barpeta Sapphire Inn", "address": "987 Barpeta, Assam"},
    {"hotel_name": "Dhubri Peaks Hotel", "address": "876 Dhubri, Assam"},
    {"hotel_name": "Diphu Valley Inn", "address": "210 Diphu, Assam"},
    {"hotel_name": "Shillong Heights", "address": "123 Shillong, Meghalaya"},
    {"hotel_name": "Cherrapunji Retreat", "address": "456 Cherrapunji, Meghalaya"},
    {"hotel_name": "Tura View Lodge", "address": "789 Tura, Meghalaya"},
    {"hotel_name": "Jowai Grand Inn", "address": "101 Jowai, Meghalaya"},
    {"hotel_name": "Nongstoin Palace", "address": "234 Nongstoin, Meghalaya"},
    {"hotel_name": "Williamnagar Meadows", "address": "567 Williamnagar, Meghalaya"},
    {"hotel_name": "Golden Valley Resort", "address": "890 Baghmara, Meghalaya"},
    {"hotel_name": "Amlarem Vista", "address": "321 Amlarem, Meghalaya"},
    {"hotel_name": "Resubelpara Hills Hotel", "address": "432 Resubelpara, Meghalaya"},
    {"hotel_name": "Khliehriat Oasis Hotel", "address": "654 Khliehriat, Meghalaya"},
    {"hotel_name": "Mairang Retreat", "address": "543 Mairang, Meghalaya"},
    {"hotel_name": "Nongpoh Palace", "address": "678 Nongpoh, Meghalaya"},
    {"hotel_name": "Baghmara Sapphire Inn", "address": "987 Baghmara, Meghalaya"},
    {"hotel_name": "Ranikor Peaks Hotel", "address": "876 Ranikor, Meghalaya"},
    {"hotel_name": "Jaintia Hills Valley Inn", "address": "210 Jaintia Hills, Meghalaya"},
    {"hotel_name": "Kohima Heights", "address": "123 Kohima, Nagaland"},
    {"hotel_name": "Dimapur Retreat", "address": "456 Dimapur, Nagaland"},
    {"hotel_name": "Mokokchung View Lodge", "address": "789 Mokokchung, Nagaland"},
    {"hotel_name": "Tuensang Grand Inn", "address": "101 Tuensang, Nagaland"},
    {"hotel_name": "Wokha Palace", "address": "234 Wokha, Nagaland"},
    {"hotel_name": "Zunheboto Meadows", "address": "567 Zunheboto, Nagaland"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Golden City, Nagaland"},
    {"hotel_name": "Peren Vista", "address": "321 Peren, Nagaland"},
    {"hotel_name": "Longleng Valley Lodge", "address": "432 Longleng, Nagaland"},
    {"hotel_name": "Kiphire Oasis Hotel", "address": "654 Kiphire, Nagaland"},
    {"hotel_name": "Mon Retreat", "address": "543 Mon, Nagaland"},
    {"hotel_name": "Phek Palace", "address": "678 Phek, Nagaland"},
    {"hotel_name": "Ziro Sapphire Inn", "address": "987 Ziro, Nagaland"},
    {"hotel_name": "Chumukedima Peaks Hotel", "address": "210 Chumukedima, Nagaland"},
    {"hotel_name": "Wokha Valley Inn", "address": "345 Wokha, Nagaland"},
    {"hotel_name": "Imphal Grand Hotel", "address": "123 Imphal, Manipur"},
    {"hotel_name": "Churachandpur Retreat Inn", "address": "456 Churachandpur, Manipur"},
    {"hotel_name": "Ukhrul Heights Hotel", "address": "789 Ukhrul, Manipur"},
    {"hotel_name": "Bishnupur Grand Inn", "address": "101 Bishnupur, Manipur"},
    {"hotel_name": "Thoubal Palace Inn", "address": "234 Thoubal, Manipur"},
    {"hotel_name": "Senapati Meadows Resort", "address": "567 Senapati, Manipur"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Golden City, Manipur"},
    {"hotel_name": "Tamenglong Vista Lodge", "address": "321 Tamenglong, Manipur"},
    {"hotel_name": "Chandel Valley Lodge", "address": "432 Chandel, Manipur"},
    {"hotel_name": "Kakching Oasis Hotel", "address": "654 Kakching, Manipur"},
    {"hotel_name": "Jiribam Retreat Inn", "address": "543 Jiribam, Manipur"},
    {"hotel_name": "Thoubal Palace Inn", "address": "678 Thoubal, Manipur"},
    {"hotel_name": "Senapati Sapphire Hotel", "address": "987 Senapati, Manipur"},
    {"hotel_name": "Tamenglong Peaks Hotel", "address": "210 Tamenglong, Manipur"},
    {"hotel_name": "Bishnupur Valley Inn", "address": "345 Bishnupur, Manipur"},
    {"hotel_name": "Aizawl Heights Hotel", "address": "123 Aizawl, Mizoram"},
    {"hotel_name": "Lunglei Retreat Inn", "address": "456 Lunglei, Mizoram"},
    {"hotel_name": "Champhai View Lodge", "address": "789 Champhai, Mizoram"},
    {"hotel_name": "Serchhip Grand Hotel", "address": "101 Serchhip, Mizoram"},
    {"hotel_name": "Kolasib Palace Inn", "address": "234 Kolasib, Mizoram"},
    {"hotel_name": "Saiha Meadows Resort", "address": "567 Saiha, Mizoram"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Golden City, Mizoram"},
    {"hotel_name": "Khawzawl Vista Lodge", "address": "321 Khawzawl, Mizoram"},
    {"hotel_name": "Mamit Valley Lodge", "address": "432 Mamit, Mizoram"},
    {"hotel_name": "Hnahthial Oasis Hotel", "address": "654 Hnahthial, Mizoram"},
    {"hotel_name": "Saitual Retreat Inn", "address": "543 Saitual, Mizoram"},
    {"hotel_name": "Saitual Palace Inn", "address": "678 Saitual, Mizoram"},
    {"hotel_name": "Serchhip Sapphire Hotel", "address": "987 Serchhip, Mizoram"},
    {"hotel_name": "Khawzawl Peaks Hotel", "address": "210 Khawzawl, Mizoram"},
    {"hotel_name": "Siaha Valley Inn", "address": "345 Siaha, Mizoram"},
    {"hotel_name": "Agartala Grand Hotel", "address": "123 Agartala, Tripura"},
    {"hotel_name": "Udaipur Retreat Inn", "address": "456 Udaipur, Tripura"},
    {"hotel_name": "Belonia Heights Hotel", "address": "789 Belonia, Tripura"},
    {"hotel_name": "Ambassa Grand Inn", "address": "101 Ambassa, Tripura"},
    {"hotel_name": "Kailashahar Palace Inn", "address": "234 Kailashahar, Tripura"},
    {"hotel_name": "Khowai Meadows Resort", "address": "567 Khowai, Tripura"},
    {"hotel_name": "Golden Hills Resort", "address": "890 Golden City, Tripura"},
    {"hotel_name": "Dharmanagar Vista Lodge", "address": "321 Dharmanagar, Tripura"},
    {"hotel_name": "Kamalpur Valley Lodge", "address": "432 Kamalpur, Tripura"},
    {"hotel_name": "Sabroom Oasis Hotel", "address": "654 Sabroom, Tripura"},
    {"hotel_name": "Ranchi Grand Hotel", "address": "123 Ranchi, Jharkhand"},
    {"hotel_name": "Jamshedpur Retreat Inn", "address": "456 Jamshedpur, Jharkhand"},
    {"hotel_name": "Dhanbad Heights Hotel", "address": "789 Dhanbad, Jharkhand"},
    {"hotel_name": "Bokaro Grand Inn", "address": "101 Bokaro, Jharkhand"},
    {"hotel_name": "Hazaribagh Palace Inn", "address": "234 Hazaribagh, Jharkhand"},
    {"hotel_name": "Giridih Meadows Resort", "address": "567 Giridih, Jharkhand"},
    {"hotel_name": "Deoghar Valley Resort", "address": "890 Deoghar, Jharkhand"},
    {"hotel_name": "Ramgarh Vista Lodge", "address": "321 Ramgarh, Jharkhand"},
    {"hotel_name": "Simdega Valley Lodge", "address": "432 Simdega, Jharkhand"},
    {"hotel_name": "Gumla Oasis Hotel", "address": "654 Gumla, Jharkhand"},
    {"hotel_name": "Latehar Retreat Inn", "address": "543 Latehar, Jharkhand"},
    {"hotel_name": "Chatra Palace Inn", "address": "678 Chatra, Jharkhand"},
    {"hotel_name": "Khunti Sapphire Hotel", "address": "987 Khunti, Jharkhand"},
    {"hotel_name": "Lohardaga Peaks Hotel", "address": "210 Lohardaga, Jharkhand"},
    {"hotel_name": "Saraikela Valley Inn", "address": "345 Saraikela, Jharkhand"},
    {"hotel_name": "Pakur Grand Hotel", "address": "123 Pakur, Jharkhand"},
    {"hotel_name": "Godda Retreat Inn", "address": "456 Godda, Jharkhand"},
    {"hotel_name": "Sahebganj Heights Hotel", "address": "789 Sahebganj, Jharkhand"},
    {"hotel_name": "Gumla Grand Inn", "address": "101 Gumla, Jharkhand"},
    {"hotel_name": "Hazaribagh Palace Inn", "address": "234 Hazaribagh, Jharkhand"},
    {"hotel_name": "Bhubaneswar Grand Hotel", "address": "123 Bhubaneswar, Odisha"},
    {"hotel_name": "Cuttack Retreat Inn", "address": "456 Cuttack, Odisha"},
    {"hotel_name": "Puri Heights Hotel", "address": "789 Puri, Odisha"},
    {"hotel_name": "Brahmapur Grand Inn", "address": "101 Brahmapur, Odisha"},
    {"hotel_name": "Sambalpur Palace Inn", "address": "234 Sambalpur, Odisha"},
    {"hotel_name": "Rourkela Meadows Resort", "address": "567 Rourkela, Odisha"},
    {"hotel_name": "Balasore Valley Resort", "address": "890 Balasore, Odisha"},
    {"hotel_name": "Jharsuguda Vista Lodge", "address": "321 Jharsuguda, Odisha"},
    {"hotel_name": "Bargarh Valley Lodge", "address": "432 Bargarh, Odisha"},
    {"hotel_name": "Rayagada Oasis Hotel", "address": "654 Rayagada, Odisha"},
    {"hotel_name": "Koraput Retreat Inn", "address": "543 Koraput, Odisha"},
    {"hotel_name": "Keonjhar Palace Inn", "address": "678 Keonjhar, Odisha"},
    {"hotel_name": "Nayagarh Sapphire Hotel", "address": "987 Nayagarh, Odisha"},
    {"hotel_name": "Kendrapara Peaks Hotel", "address": "210 Kendrapara, Odisha"},
    {"hotel_name": "Mayurbhanj Valley Inn", "address": "345 Mayurbhanj, Odisha"},
    {"hotel_name": "Nabarangpur Grand Hotel", "address": "123 Nabarangpur, Odisha"},
    {"hotel_name": "Phulbani Retreat Inn", "address": "456 Phulbani, Odisha"},
    {"hotel_name": "Dhenkanal Heights Hotel", "address": "789 Dhenkanal, Odisha"},
    {"hotel_name": "Boudh Grand Inn", "address": "101 Boudh, Odisha"},
    {"hotel_name": "Sonepur Palace Inn", "address": "234 Sonepur, Odisha"},
    {"hotel_name": "Ahmedabad Grand Hotel", "address": "123 Ahmedabad, Gujarat"},
    {"hotel_name": "Surat Retreat Inn", "address": "456 Surat, Gujarat"},
    {"hotel_name": "Vadodara Heights Hotel", "address": "789 Vadodara, Gujarat"},
    {"hotel_name": "Rajkot Grand Inn", "address": "101 Rajkot, Gujarat"},
    {"hotel_name": "Bhavnagar Palace Inn", "address": "234 Bhavnagar, Gujarat"},
    {"hotel_name": "Jamnagar Meadows Resort", "address": "567 Jamnagar, Gujarat"},
    {"hotel_name": "Gandhinagar Valley Resort", "address": "890 Gandhinagar, Gujarat"},
    {"hotel_name": "Junagadh Vista Lodge", "address": "321 Junagadh, Gujarat"},
    {"hotel_name": "Porbandar Valley Lodge", "address": "432 Porbandar, Gujarat"},
    {"hotel_name": "Anand Oasis Hotel", "address": "654 Anand, Gujarat"},
    {"hotel_name": "Bharuch Retreat Inn", "address": "543 Bharuch, Gujarat"},
    {"hotel_name": "Gandhidham Palace Inn", "address": "678 Gandhidham, Gujarat"},
    {"hotel_name": "Bhuj Sapphire Hotel", "address": "987 Bhuj, Gujarat"},
    {"hotel_name": "Vapi Peaks Hotel", "address": "210 Vapi, Gujarat"},
    {"hotel_name": "Navsari Valley Inn", "address": "345 Navsari, Gujarat"},
    {"hotel_name": "Ankleshwar Grand Hotel", "address": "123 Ankleshwar, Gujarat"},
    {"hotel_name": "Morbi Retreat Inn", "address": "456 Morbi, Gujarat"},
    {"hotel_name": "Valsad Heights Hotel", "address": "789 Valsad, Gujarat"},
    {"hotel_name": "Gir Somnath Grand Inn", "address": "101 Gir Somnath, Gujarat"},
    {"hotel_name": "Dahod Palace Inn", "address": "234 Dahod, Gujarat"},
    {"hotel_name": "Bhopal Grand Hotel", "address": "123 Bhopal, Madhya Pradesh"},
    {"hotel_name": "Indore Retreat Inn", "address": "456 Indore, Madhya Pradesh"},
    {"hotel_name": "Jabalpur Heights Hotel", "address": "789 Jabalpur, Madhya Pradesh"},
    {"hotel_name": "Gwalior Grand Inn", "address": "101 Gwalior, Madhya Pradesh"},
    {"hotel_name": "Ujjain Palace Inn", "address": "234 Ujjain, Madhya Pradesh"},
    {"hotel_name": "Sagar Meadows Resort", "address": "567 Sagar, Madhya Pradesh"},
    {"hotel_name": "Satna Valley Resort", "address": "890 Satna, Madhya Pradesh"},
    {"hotel_name": "Rewa Vista Lodge", "address": "321 Rewa, Madhya Pradesh"},
    {"hotel_name": "Katni Valley Lodge", "address": "432 Katni, Madhya Pradesh"},
    {"hotel_name": "Chhindwara Oasis Hotel", "address": "654 Chhindwara, Madhya Pradesh"},
    {"hotel_name": "Guna Retreat Inn", "address": "543 Guna, Madhya Pradesh"},
    {"hotel_name": "Morena Palace Inn", "address": "678 Morena, Madhya Pradesh"},
    {"hotel_name": "Shivpuri Sapphire Hotel", "address": "987 Shivpuri, Madhya Pradesh"},
    {"hotel_name": "Damoh Peaks Hotel", "address": "210 Damoh, Madhya Pradesh"},
    {"hotel_name": "Mandsaur Valley Inn", "address": "345 Mandsaur, Madhya Pradesh"},
    {"hotel_name": "Khandwa Grand Hotel", "address": "123 Khandwa, Madhya Pradesh"},
    {"hotel_name": "Burhanpur Retreat Inn", "address": "456 Burhanpur, Madhya Pradesh"},
    {"hotel_name": "Neemuch Heights Hotel", "address": "789 Neemuch, Madhya Pradesh"},
    {"hotel_name": "Seoni Grand Inn", "address": "101 Seoni, Madhya Pradesh"},
    {"hotel_name": "Betul Palace Inn", "address": "234 Betul, Madhya Pradesh"},
    {"hotel_name": "Raipur Grand Hotel", "address": "123 Raipur, Chhattisgarh"},
    {"hotel_name": "Bhilai Retreat Inn", "address": "456 Bhilai, Chhattisgarh"},
    {"hotel_name": "Bilaspur Heights Hotel", "address": "789 Bilaspur, Chhattisgarh"},
    {"hotel_name": "Korba Grand Inn", "address": "101 Korba, Chhattisgarh"},
    {"hotel_name": "Raigarh Palace Inn", "address": "234 Raigarh, Chhattisgarh"},
    {"hotel_name": "Durg Meadows Resort", "address": "567 Durg, Chhattisgarh"},
    {"hotel_name": "Rajnandgaon Valley Resort", "address": "890 Rajnandgaon, Chhattisgarh"},
    {"hotel_name": "Jagdalpur Vista Lodge", "address": "321 Jagdalpur, Chhattisgarh"},
    {"hotel_name": "Ambikapur Valley Lodge", "address": "432 Ambikapur, Chhattisgarh"},
    {"hotel_name": "Korba Oasis Hotel", "address": "654 Korba, Chhattisgarh"},
    {"hotel_name": "Taj Mahal Palace", "address": "Apollo Bunder, Mumbai, Maharashtra"},
    {"hotel_name": "The Oberoi", "address": "Nariman Point, Mumbai, Maharashtra"},
    {"hotel_name": "JW Marriott Mumbai Juhu", "address": "Juhu Tara Road, Mumbai, Maharashtra"},
    {"hotel_name": "The Leela Mumbai", "address": "Sahar, Mumbai, Maharashtra"},
    {"hotel_name": "ITC Grand Central", "address": "Parel, Mumbai, Maharashtra"},
    {"hotel_name": "Grand Hyatt Mumbai", "address": "Santacruz East, Mumbai, Maharashtra"},
    {"hotel_name": "Novotel Mumbai Juhu Beach", "address": "Juhu Beach, Mumbai, Maharashtra"},
    {"hotel_name": "Sofitel Mumbai BKC", "address": "Bandra Kurla Complex, Mumbai, Maharashtra"},
    {"hotel_name": "Trident Nariman Point", "address": "Nariman Point, Mumbai, Maharashtra"},
    {"hotel_name": "Hyatt Regency Mumbai", "address": "Sahar, Mumbai, Maharashtra"},
    {"hotel_name": "Taj Lands End", "address": "Bandra West, Mumbai, Maharashtra"},
    {"hotel_name": "The St. Regis Mumbai", "address": "Lower Parel, Mumbai, Maharashtra"},
    {"hotel_name": "Renaissance Mumbai Convention Centre Hotel", "address": "Powai, Mumbai, Maharashtra"},
    {"hotel_name": "Four Seasons Hotel Mumbai", "address": "Worli, Mumbai, Maharashtra"},
    {"hotel_name": "Taj Santacruz", "address": "Santacruz East, Mumbai, Maharashtra"},
    {"hotel_name": "The Lalit Mumbai", "address": "Andheri East, Mumbai, Maharashtra"},
    {"hotel_name": "InterContinental Marine Drive", "address": "Marine Drive, Mumbai, Maharashtra"},
    {"hotel_name": "Holiday Inn Mumbai International Airport", "address": "Sakinaka, Mumbai, Maharashtra"},
    {"hotel_name": "Courtyard by Marriott Mumbai International Airport", "address": "Andheri East, Mumbai, Maharashtra"},
    {"hotel_name": "Ramada Plaza Palm Grove", "address": "Juhu Beach, Mumbai, Maharashtra"},
    {"hotel_name": "Taj West End", "address": "Race Course Road, Bangalore, Karnataka"},
    {"hotel_name": "The Oberoi, Bengaluru", "address": "MG Road, Bangalore, Karnataka"},
    {"hotel_name": "ITC Gardenia", "address": "Residency Road, Bangalore, Karnataka"},
    {"hotel_name": "JW Marriott Hotel Bengaluru", "address": "Vittal Mallya Road, Bangalore, Karnataka"},
    {"hotel_name": "The Leela Palace Bengaluru", "address": "Old Airport Road, Bangalore, Karnataka"},
    {"hotel_name": "Taj MG Road, Bengaluru", "address": "MG Road, Bangalore, Karnataka"},
    {"hotel_name": "Sheraton Grand Bangalore Hotel at Brigade Gateway", "address": "Malleswaram, Bangalore, Karnataka"},
    {"hotel_name": "Ritz-Carlton, Bangalore", "address": "Residency Road, Bangalore, Karnataka"},
    {"hotel_name": "Grand Mercure Bangalore", "address": "Koramangala, Bangalore, Karnataka"},
    {"hotel_name": "Hyatt Centric MG Road Bangalore", "address": "MG Road, Bangalore, Karnataka"},
    {"hotel_name": "Vivanta Bengaluru Residency Road", "address": "Residency Road, Bangalore, Karnataka"},
    {"hotel_name": "Le Méridien Bangalore", "address": "Sankey Road, Bangalore, Karnataka"},
    {"hotel_name": "The Chancery Pavilion", "address": "Residency Road, Bangalore, Karnataka"},
    {"hotel_name": "Courtyard by Marriott Bengaluru Outer Ring Road", "address": "Marathahalli, Bangalore, Karnataka"},
    {"hotel_name": "The Lalit Ashok", "address": "Kumara Krupa High Grounds, Bangalore, Karnataka"},
    {"hotel_name": "Hyatt Bangalore MG Road", "address": "MG Road, Bangalore, Karnataka"},
    {"hotel_name": "Crowne Plaza Bengaluru Electronics City", "address": "Electronics City, Bangalore, Karnataka"},
    {"hotel_name": "Holiday Inn Bengaluru Racecourse", "address": "Race Course Road, Bangalore, Karnataka"},
    {"hotel_name": "Taj Yeshwantpur, Bengaluru", "address": "Yeshwanthpur, Bangalore, Karnataka"},
    {"hotel_name": "The Zuri Whitefield Bengaluru", "address": "Whitefield, Bangalore, Karnataka"},
    {"hotel_name": "Taj Coromandel", "address": "Nungambakkam, Chennai, Tamil Nadu"},
    {"hotel_name": "ITC Grand Chola", "address": "Guindy, Chennai, Tamil Nadu"},
    {"hotel_name": "The Leela Palace Chennai", "address": "Adyar, Chennai, Tamil Nadu"},
    {"hotel_name": "Park Hyatt Chennai", "address": "Guindy, Chennai, Tamil Nadu"},
    {"hotel_name": "Hyatt Regency Chennai", "address": "Anna Salai, Chennai, Tamil Nadu"},
    {"hotel_name": "Hilton Chennai", "address": "Guindy, Chennai, Tamil Nadu"},
    {"hotel_name": "The Raintree Hotel, St. Mary's Road", "address": "St. Mary's Road, Chennai, Tamil Nadu"},
    {"hotel_name": "Radisson Blu Hotel Chennai City Centre", "address": "Egmore, Chennai, Tamil Nadu"},
    {"hotel_name": "The Accord Metropolitan", "address": "T. Nagar, Chennai, Tamil Nadu"},
    {"hotel_name": "The Westin Chennai Velachery", "address": "Velachery, Chennai, Tamil Nadu"},
    {"hotel_name": "Ramada Chennai Egmore", "address": "Egmore, Chennai, Tamil Nadu"},
    {"hotel_name": "Novotel Chennai Chamiers Road", "address": "Chamiers Road, Chennai, Tamil Nadu"},
    {"hotel_name": "Aloft Chennai OMR IT Expressway", "address": "OMR IT Expressway, Chennai, Tamil Nadu"},
    {"hotel_name": "Courtyard by Marriott Chennai", "address": "Anna Salai, Chennai, Tamil Nadu"},
    {"hotel_name": "The Checkers Hotel", "address": "Nandanam, Chennai, Tamil Nadu"},
    {"hotel_name": "Hablis Chennai", "address": "Guindy, Chennai, Tamil Nadu"},
    {"hotel_name": "GRT Grand Chennai", "address": "T. Nagar, Chennai, Tamil Nadu"},
    {"hotel_name": "The Spring Hotel", "address": "Nungambakkam, Chennai, Tamil Nadu"},
    {"hotel_name": "Hotel Savera", "address": "Radhakrishnan Salai, Chennai, Tamil Nadu"},
    {"hotel_name": "Green Park Chennai", "address": "Vadapalani, Chennai, Tamil Nadu"},
    {"hotel_name": "Taj Connemara", "address": "Chennai, Tamil Nadu"},
    {"hotel_name": "The Tamara Kodai", "address": "Kodaikanal, Tamil Nadu"},
    {"hotel_name": "The Windflower Resort and Spa, Coorg", "address": "Coorg, Tamil Nadu"},
    {"hotel_name": "Raj Park Tirupati", "address": "Tirupati, Tamil Nadu"},
    {"hotel_name": "Great Trails Yercaud by GRT Hotels", "address": "Yercaud, Tamil Nadu"},
    {"hotel_name": "WelcomHotel Coimbatore", "address": "Coimbatore, Tamil Nadu"},
    {"hotel_name": "The Accord Salem", "address": "Salem, Tamil Nadu"},
    {"hotel_name": "The Gateway Hotel Pasumalai", "address": "Madurai, Tamil Nadu"},
    {"hotel_name": "Sparsa Thiruvannamalai", "address": "Thiruvannamalai, Tamil Nadu"},
    {"hotel_name": "The Bangala, Karaikudi", "address": "Karaikudi, Tamil Nadu"},
    {"hotel_name": "Esthell Village Resort", "address": "Mahabalipuram, Tamil Nadu"},
    {"hotel_name": "The Residency Towers, Coimbatore", "address": "Coimbatore, Tamil Nadu"},
    {"hotel_name": "Hotel Tamilnadu, Rameswaram", "address": "Rameswaram, Tamil Nadu"},
    {"hotel_name": "Hotel SSK Grand", "address": "Madurai, Tamil Nadu"},
    {"hotel_name": "Hotel Royal Park", "address": "Tirupur, Tamil Nadu"},
    {"hotel_name": "Grand Palace Hotel and Spa, Yercaud", "address": "Yercaud, Tamil Nadu"},
    {"hotel_name": "Hotel Palmgrove", "address": "Chennai, Tamil Nadu"},
    {"hotel_name": "Svatma, Thanjavur", "address": "Thanjavur, Tamil Nadu"},
    {"hotel_name": "Sterling Ooty Fern Hill", "address": "Ooty, Tamil Nadu"},
    {"hotel_name": "Hotel GRT Regency Madurai", "address": "Madurai, Tamil Nadu"},
    {"hotel_name": "Taj Falaknuma Palace", "address": "Engine Bowli, Falaknuma, Hyderabad, Telangana"},
    {"hotel_name": "Park Hyatt Hyderabad", "address": "Banjara Hills, Hyderabad, Telangana"},
    {"hotel_name": "ITC Kohenur", "address": "Madhapur, Hyderabad, Telangana"},
    {"hotel_name": "Taj Krishna", "address": "Banjara Hills, Hyderabad, Telangana"},
    {"hotel_name": "Hyatt Hyderabad Gachibowli", "address": "Gachibowli, Hyderabad, Telangana"},
    {"hotel_name": "Novotel Hyderabad Convention Centre", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Marriott Hyderabad", "address": "Tank Bund Road, Hyderabad, Telangana"},
    {"hotel_name": "The Westin Hyderabad Mindspace", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Golkonda Resorts and Spa", "address": "Gandipet, Hyderabad, Telangana"},
    {"hotel_name": "Radisson Blu Plaza Hotel Hyderabad Banjara Hills", "address": "Banjara Hills, Hyderabad, Telangana"},
    {"hotel_name": "Avasa Hotel", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Trident Hyderabad", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Lemon Tree Premier, HITEC City, Hyderabad", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Hyderabad Marriott Hotel and Convention Centre", "address": "Tank Bund Road, Hyderabad, Telangana"},
    {"hotel_name": "Radisson Hyderabad Hitec City", "address": "Hitec City, Hyderabad, Telangana"},
    {"hotel_name": "Taj Deccan", "address": "Banjara Hills, Hyderabad, Telangana"},
    {"hotel_name": "Daspalla Hotel", "address": "Jubilee Hills, Hyderabad, Telangana"},
    {"hotel_name": "Fortune Park Vallabha", "address": "Banjara Hills, Hyderabad, Telangana"},
    {"hotel_name": "Hyderabad Marriott Hotel", "address": "Tank Bund Road, Hyderabad, Telangana"},
    {"hotel_name": "Hotel Green Park", "address": "Ameerpet, Hyderabad, Telangana"},
    {"hotel_name": "Taj Malabar Resort & Spa, Cochin", "address": "Willingdon Island, Cochin, Kerala"},
    {"hotel_name": "The Leela Kovalam Beach", "address": "Kovalam, Kerala"},
    {"hotel_name": "Vivanta by Taj - Bekal", "address": "Bekal, Kerala"},
    {"hotel_name": "The Raviz Resort and Spa, Ashtamudi", "address": "Ashtamudi, Kerala"},
    {"hotel_name": "Kumarakom Lake Resort", "address": "Kumarakom, Kerala"},
    {"hotel_name": "Niraamaya Retreats Surya Samudra, Kovalam", "address": "Kovalam, Kerala"},
    {"hotel_name": "Grand Hyatt Kochi Bolgatty", "address": "Bolgatty Island, Cochin, Kerala"},
    {"hotel_name": "The Lalit Resort & Spa, Bekal", "address": "Bekal, Kerala"},
    {"hotel_name": "Zuri Kumarakom", "address": "Kumarakom, Kerala"},
    {"hotel_name": "Taj Kumarakom Resort & Spa", "address": "Kumarakom, Kerala"},
    {"hotel_name": "Kadmat Island Beach Resort", "address": "Lakshadweep, Kerala"},
    {"hotel_name": "The Gateway Hotel Beach Road Calicut", "address": "Calicut, Kerala"},
    {"hotel_name": "Lake Palace, Thekkady", "address": "Thekkady, Kerala"},
    {"hotel_name": "Coco Lagoon by Great Mount Resort", "address": "Pollachi, Kerala"},
    {"hotel_name": "Turtle on the Beach", "address": "Kovalam, Kerala"},
    {"hotel_name": "Ramada Alleppey", "address": "Alleppey, Kerala"},
    {"hotel_name": "Tree of Life Marari Sands Beach Resort", "address": "Mararikulam, Kerala"},
    {"hotel_name": "Forte Kochi", "address": "Fort Kochi, Kerala"},
    {"hotel_name": "Parakkat Nature Hotels & Resorts", "address": "Munnar, Kerala"},
    {"hotel_name": "Xandari Pearl", "address": "Mararikulam, Kerala"}
]
hotel_descriptions = [
    {
        "description": "Discover a peaceful retreat where relaxation meets natural beauty. Our hotel is nestled in a serene location, providing a tranquil atmosphere for your stay."
    },
    {
        "description": "Experience the perfect blend of modern comfort and timeless elegance. Our hotel offers luxurious accommodations and impeccable service."
    },
    {
        "description": "Escape to a world of enchantment and serenity. Whether you seek adventure or relaxation, our hotel caters to your every need."
    },
    {
        "description": "Unwind and rejuvenate in a haven of tranquility. Our hotel's spa offers a range of treatments to refresh your body and mind."
    },
    {
        "description": "Indulge in culinary delights at our world-class restaurants. From local specialties to international cuisine, our chefs create dishes that delight the senses."
    },
    {
        "description": "Explore the natural beauty that surrounds our hotel. With hiking trails and outdoor activities, there's always an adventure waiting."
    },
    {
        "description": "Plan your dream event with us. Our event planners are dedicated to making your special occasion truly memorable."
    },
    {
        "description": "Enjoy the convenience of our central location, providing easy access to the city's attractions and cultural landmarks."
    },
    {
        "description": "Reconnect with nature in our lush gardens and scenic landscapes. Our hotel is a paradise for those seeking peace and serenity."
    },
    {
        "description": "Embark on a journey of relaxation and self-discovery. Our wellness programs and holistic therapies are designed to revitalize your spirit."
    },
    {
        "description": "Experience the magic of our charming accommodations. Whether you choose a cozy room or a spacious suite, comfort is our priority."
    },
    {
        "description": "Unwind by the poolside and enjoy breathtaking views of the sunset. Our infinity pool offers a perfect way to relax and soak in the beauty of the surroundings."
    },
    {
        "description": "Immerse yourself in the local culture and traditions. Our hotel offers cultural experiences and activities to enhance your stay."
    },
    {
        "description": "Host your business meetings and conferences with ease. Our state-of-the-art facilities and attentive staff ensure successful events."
    },
    {
        "description": "Experience the warmth and hospitality of our friendly staff. Your comfort and satisfaction are our top priorities."
    },
    {
        "description": "Discover hidden gems and secret spots with our guided tours. Let us show you the best our destination has to offer."
    },
    {
        "description": "Savor the flavors of our region at our on-site restaurant. Our chef's creations are a culinary journey you won't want to miss."
    },
    {
        "description": "Relax in the heart of nature with our eco-friendly accommodations. We're committed to sustainability and preserving the environment."
    },
    {
        "description": "Create lasting memories with loved ones at our family-friendly hotel. From spacious suites to kids' activities, we cater to families of all sizes."
    },
    {
        "description": "Experience a touch of luxury in every aspect of your stay. Our attention to detail and personalized service make your visit extraordinary."
    }
]



photo_urls = [
    "Images\hotel1.jpg",
    "Images\hotel2.jpg",
    "Images\hotel3.jpg",
    "Images\hotel4.jpg",
    "Images\hotel5.jpg",
    "Images\hotel6.jpg",
    "Images\hotel7.jpg",
    "Images\hotel8.jpg",
    "Images\hotel9.jpg",
    "Images\hotel10.jpg",

    # Add more photo URLs here
]






rooms = []
room_types = ['Standard Room', 'Deluxe Room', 'Superior room', 'Exceutive Room', 'Family Room', 'Presidential Suite', 'Suite', 'Adjoining Rooms', 'Accessible Room']
for i in range(1, 521):
    room_cost = [0]*9
    z = random.randint(10, 25)
    room_cost[0] = z*100
    z = random.randint(25, 35)
    room_cost[1] = z*100
    z = random.randint(35, 45)
    room_cost[2] = z*100
    z = random.randint(45, 50)
    room_cost[3] = z*100
    z = random.randint(25, 40)
    room_cost[4] = z*100
    z = random.randint(50, 100)
    room_cost[5] = z*1000
    z = random.randint(15, 25)
    room_cost[6] = z*1000
    z = random.randint(45, 60)
    room_cost[7] = z*100
    z = random.randint(15, 30)
    room_cost[8] = z*100   
    x = random.randint(5, 15)
    room_n = x*10
    sum = 0
    for j in range(1, room_n):
        dict = {}
        dict['Room_Num'] = j
        dict['Hotel_ID'] = i
        probabilities = [7/45] * 5 + [1/18] * 4  # Probabilities for numbers 0 to 4 and 5 to 8
        y = random.choices(range(9), probabilities)[0]
        dict['Room_type'] = room_types[y]
        dict['Cost'] = room_cost[y]
        cap = random.randint(2, 5)
        dict['Room_Capacity'] = cap
        sum += cap
        rooms.append(dict)
    hotels[i-1]['hotel_ID'] = i
    hotels[i-1]['Capacity'] = sum
    rat = random.randint(25, 50)
    hotels[i-1]['Rating'] = rat/10
    des = random.randint(0, 19)
    hotels[i-1]['Description'] = hotel_descriptions[des]['description']
    
    # Select a random photo URL from the list
    random_photo_url = random.choice(photo_urls)
    hotels[i-1]['photourl'] = random_photo_url

    # Extract the city name from the address
    address_parts = hotels[i-1]['address'].split(',')
    if len(address_parts) > 1:
        city = address_parts[-2].strip()
        hotels[i-1]['city'] = city
    
df = pd.DataFrame(hotels)
df = df[['hotel_ID','hotel_name', 'address', 'city', 'hotel_ID', 'Capacity', 'Rating', 'Description', 'photourl']]
df.to_csv('hotels.csv', index=False)

df = pd.DataFrame(rooms)
df.to_csv('rooms.csv', index=False)